################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
tests/modif \
tests/gen \
tests/fit \
tests/eval \
tests/ea \
tests/ctrl \
sferes/dbg \
modules/nn2 \
modules/nn \
modules/modularity \
modules/modularity/grc \
modules/fastsim \
modules/cartpole \
exp/mole_exp \
exp/modularity \
exp/modularity/researchfiles \
exp/map_elite_cost \
exp/map_elite \
exp/example \
exp/deep_learning \
exp/deep_learning/ale/src/os_dependent \
exp/deep_learning/ale/src \
exp/deep_learning/ale/src/games/supported \
exp/deep_learning/ale/src/games \
exp/deep_learning/ale/src/emucore \
exp/deep_learning/ale/src/emucore/rsynth \
exp/deep_learning/ale/src/emucore/m6502/src \
exp/deep_learning/ale/src/control \
exp/deep_learning/ale/src/common \
exp/deep_learning/ale/src/agents \
exp/Normalized_hierarchy/network_toolbox-master/src \
exp/Normalized_hierarchy/network_toolbox-master/build/src \
examples \
doc/build/v2/test/v1_testing \
doc/build/v2/test/v1-testing \
doc/build/v2/test/unused \
doc/build/v2/test/test2 \
doc/build/v2/test/railsys/program/main \
doc/build/v2/test/railsys/program/liba \
doc/build/v2/test/railsys/libx/src \
doc/build/v2/test/qt4 \
doc/build/v2/test/project-test4/lib \
doc/build/v2/test/project-test4 \
doc/build/v2/test/project-test3/lib3 \
doc/build/v2/test/project-test3/lib2/helper \
doc/build/v2/test/project-test3/lib2 \
doc/build/v2/test/project-test3/lib \
doc/build/v2/test/project-test3 \
doc/build/v2/test/prebuilt \
doc/build/v2/test/prebuilt/ext \
doc/build/v2/test/generators-test \
doc/build/v2/test/generators-test/lib \
doc/build/v2/test/direct-request-test \
doc/build/v2/test/dependency-test \
doc/build/v2/example/versioned \
doc/build/v2/example/variant/libs \
doc/build/v2/example/variant \
doc/build/v2/example/qt/qt4/uic \
doc/build/v2/example/qt/qt4/moccable-cpp \
doc/build/v2/example/qt/qt4/hello \
doc/build/v2/example/qt/qt3/uic \
doc/build/v2/example/qt/qt3/moccable-cpp \
doc/build/v2/example/qt/qt3/hello \
doc/build/v2/example/pch/source \
doc/build/v2/example/libraries/util/foo \
doc/build/v2/example/libraries/app \
doc/build/v2/example/hello \
doc/build/v2/example/gettext \
doc/build/v2/example/generate \
doc/build/v2/example/customization \
doc/build/v2/example/built_tool/tblgen \
doc/build/v2/example/built_tool/core \
doc/build/v2/engine \
doc/build/v2/engine/modules \
doc/build/v2/engine/boehm_gc \
doc/build/v2/engine/boehm_gc/tests \
doc/build/v2/engine/boehm_gc/cord \
doc/build/v2/engine/boehm_gc/Mac_files \
build/default/tests/modif \
build/default/tests/gen \
build/default/tests/fit \
build/default/tests/eval \
build/default/tests/ea \
build/default/tests/ctrl \
build/default/sferes/dbg \
build/default/modules/nn2 \
build/default/exp/modularity \
build/default/examples \
build/debug/tests/modif \
build/debug/tests/gen \
build/debug/tests/fit \
build/debug/tests/eval \
build/debug/tests/ea \
build/debug/tests/ctrl \
build/debug/sferes/dbg \
build/debug/modules/nn2 \
build/debug/exp/modularity \
build/debug/examples \
build/.conf_check_0/testbuild/default \
build/.conf_check_0 \

